---

- name: Set hostname
  environment: "{{ system_env | default({}) }}"
  become: true
  block:

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ system_hostname }}"
      when:
        - system_hostname is defined
        - ansible_facts['os_family'] in ['Archlinux', 'Debian', 'FreeBSD', 'RedHat', 'Suse']
