---

- name: Set timezone
  environment: "{{ system_env | default({}) }}"
  become: true
  block:

    - name: Set timezone # noqa: ignore-errors
      community.general.timezone:
        name: "{{ system_timezone }}"
      when:
        - system_timezone is defined
        - ansible_facts['os_family'] in ['Alpine', 'Archlinux', 'Debian', 'FreeBSD', 'RedHat', 'Suse']
      ignore_errors: true
